# Generated by Django 3.2.9 on 2021-12-04 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('cantidad', models.IntegerField(default=1)),
                ('uid_item_cart', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('Pizza', 'Pizza'), ('Topping', 'Topping'), ('Sub', 'Sub'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Cena', 'Cena'), ('Extra', 'Extra')], max_length=32)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cuenta_func',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('nombre', models.CharField(max_length=128)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6)),
                ('tamanio', models.CharField(choices=[(' Pequeño', 'Pequeño'), ('Grande', 'Grande'), ('Tamaño_unico', 'Tamaño_unico')], max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.elemento')),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'Cena',
            },
            bases=('orders.elemento',),
        ),
        migrations.CreateModel(
            name='Ensalda',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.elemento')),
            ],
            options={
                'verbose_name': 'Ensalada',
                'verbose_name_plural': 'Ensaladas',
            },
            bases=('orders.elemento',),
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.elemento')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
            },
            bases=('orders.elemento',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.elemento')),
            ],
            options={
                'verbose_name': 'Pasta',
                'verbose_name_plural': 'Pastas',
            },
            bases=('orders.elemento',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.elemento')),
                ('toppingN', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=50)),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
            },
            bases=('orders.elemento',),
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.elemento')),
            ],
            options={
                'verbose_name': 'Sub',
                'verbose_name_plural': 'Subs',
            },
            bases=('orders.elemento',),
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('elemento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.elemento')),
            ],
            options={
                'verbose_name': 'Topping',
                'verbose_name_plural': 'Toppings',
            },
            bases=('orders.elemento',),
        ),
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=16)),
                ('estado', models.CharField(choices=[('Carrito', 'Carrito'), ('En proceso', 'En proceso'), ('Enviada', 'Enviada'), ('Recibida', 'Recibida'), ('Orden', 'Orden')], default='Carrito', max_length=20)),
                ('items', models.ManyToManyField(related_name='items_orden', to='orders.CarritoItem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.elemento'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='extra_name',
            field=models.ManyToManyField(blank=True, related_name='extra_carrito', to='orders.Extra'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='toppings_carrito', to='orders.Topping'),
        ),
    ]
