# Generated by Django 3.2.9 on 2021-11-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='precio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='tamanio',
            field=models.CharField(choices=[(' Pequeño', 'Pequeño'), ('Grande', 'Grande')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='tipo',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=50),
        ),
    ]
