# Generated by Django 3.2.9 on 2021-12-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_carritoitem_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritoitem',
            old_name='topping',
            new_name='toppingPizza',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='extra_name',
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='extras_name',
            field=models.ManyToManyField(blank=True, related_name='extras_carrito', to='orders.Extra'),
        ),
        migrations.AddField(
            model_name='orden',
            name='tipo',
            field=models.CharField(choices=[('Carrito', 'Carrito'), ('Orden', 'Orden')], default='Carrito', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Enviada', 'Enviada'), ('Recibida', 'Recibida')], default='En proceso', max_length=20),
        ),
    ]
