# Generated by Django 3.2.9 on 2021-12-05 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211205_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='cantidad',
        ),
    ]
