# Generated by Django 3.2.9 on 2021-12-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_carritoitem_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orden'),
        ),
    ]
