# Generated by Django 3.2.9 on 2021-12-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_carritoitem_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='monto_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
