# Generated by Django 3.2.9 on 2021-12-16 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_carritoitem_monto_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='tipo_pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_carrito', to='orders.pizza'),
        ),
    ]
