# Generated by Django 3.2.9 on 2021-12-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211216_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tipo',
            field=models.CharField(choices=[('Carrito', 'Carrito'), ('Orden', 'Orden')], default='Carrito', max_length=20),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='tipo_pizza',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
